version: "3"

services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ../backend-api
    volumes:
      - /app/node_modules
      - ../backend-api:/app
    ports:
      - "8080:8080"
